app:
  name: "XSS Hunter Pro"
  version: "1.0.0"
  environment: "development"
  debug: true

security:
  secret_key: "your-secret-key-here"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  password_min_length: 12

database:
  mongodb_url: "mongodb://localhost:27017"
  database_name: "xsshunterpro"
  collections:
    scans: "scans"
    users: "users"
    reports: "reports"
    payloads: "payloads"

scanner:
  timeout: 30
  max_threads: 10
  user_agent: "XSSHunterPro/1.0"
  verify_ssl: true
  follow_redirects: true
  max_redirects: 5
  
  # Detection parameters
  detection:
    dom_parsing: true
    reflected_xss: true
    stored_xss: true
    dom_xss: true
    blind_xss: false
    
  # Scan limits
  limits:
    max_urls_per_scan: 100
    max_depth: 3
    max_parameters: 20
    request_delay: 0.5

payloads:
  # Basic payloads
  basic:
    - "<script>alert('XSS')</script>"
    - "<img src=x onerror=alert('XSS')>"
    - "javascript:alert('XSS')"
  
  # Advanced payloads
  advanced:
    - "<svg/onload=alert('XSS')>"
    - "'-alert('XSS')-'"
    - "<img src=x oneonerrorrror=alert('XSS')>"
  
  # Payloads for WAF bypass
  waf_bypass:
    - "<svG/onload=prompt(1)>"
    - "javas&#99;ript:alert(1)"
    - "<img src=x onerror=\\x61lert('XSS')>"

reporting:
  output_dir: "reports"
  formats:
    - "html"
    - "pdf"
    - "json"
  include_screenshots: true
  risk_levels:
    - "Critical"
    - "High"
    - "Medium"
    - "Low"
    - "Info"

api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  rate_limit:
    requests: 100
    period: 60

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/xsshunterpro.log"
  max_size: 10485760  # 10MB
  backup_count: 5 